Inline Put, Push, Ack, Confirm
bloomberg/blazingmq pull request #177
Opened 2023-12-22 20:39 UTC by dorjesinpo

Messages that have fixed destination (such as PUSH/ACK/Relay PUT/Relay CONFIRM) do not have to go on Cluster thread - it is a bottleneck.
Instead, messages can go directly to mqbnet::Channel which enqueues them in thread-safe manner.
This needs synchronization based on AtomicGate which allows thread-safe, efficient checking of the cluster status and thread-safe opening/closing and draining.

PUSH and ACK require statistics update which we move from Cluster to Queue. For this reason the opening queue context (OpenQueueConfirmationCookie) conveys statistics from Queue to Cluster

2024-01-04 11:07 UTC, 678098 commented
Hi @dorjesinpo, looking

2024-01-08 13:06 UTC, 678098 commented on src/groups/mqb/mqbblp/mqbblp_queuehandle.cpp
> +                          << "']";
This log line is logged only when we don't have an inline client, is it okay? The same is true for other logs later in this method.

2024-01-08 13:07 UTC, 678098 commented on src/groups/mqb/mqbblp/mqbblp_queuehandle.cpp
> +                      << " with error: " << result;
This is logged only when we don't have an inline client, is it okay to skip that case for logging?

2024-01-10 17:41 UTC, dorjesinpo reviewed
Thank you for reviewing!

2024-01-10 21:04 UTC, 678098 commented on src/groups/mqb/mqbblp/mqbblp_clusterproxy.cpp
> +    d_activeNode_p = activeNode;
Maybe it's worth it to describe this in docs for `d_activeNode_p`

2024-01-10 21:18 UTC, 678098 commented on src/groups/mqb/mqbblp/mqbblp_clusterproxy.cpp
> +        BALL_LOG_ERROR << "#UNEXPECTED_EVENT " << description();
Can be done this way. About `not yet`, we have this log for PUT event log near

2024-01-10 21:19 UTC, 678098 commented
@dorjesinpo thank you for fixes, added some comments in discussions and reassigned. You can assign this to @quarter-note later

2024-12-18 22:32 UTC, pniedzielski commented
Assigning back to @dorjesinpo (to put in backlog)

2025-07-07 15:27 UTC, 678098 requested changes

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbmock/mqbmock_cluster.cpp
> +    BSLS_ANNOTATION_UNUSED const bmqp::ConfirmMessage& message)
```suggestion
    BSLA_UNUSED int   partitionId,
    BSLA_UNUSED const bmqp::ConfirmMessage& message)
```
Recent changes

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbmock/mqbmock_cluster.cpp
> +                        genCount);
I think there will be a segfault if we try to call a function that is not set. At least this is how it was in std c++ implementation.

Do you think it's worth handling empty `d_putFunctor` for this mock class?

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbmock/mqbmock_cluster.cpp
> +, d_putFunctor()
```suggestion
, d_putFunctor(bsl::allocator_arg, d_allocator_p)
```
Need to handle possibly non-default allocator. This allocator will also be used in `operator=`

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbmock/mqbmock_cluster.h
> +    // handle on which it is being executed.
I think this comment is misleading, since there is more than 1 parameter.
We can remove it or place the updated version in `///` block before `PutFunctor`

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbi/mqbi_queue.h
> +    case e_INVALID_GEN_COUNT: BSLS_ANNOTATION_FALLTHROUGH;
```suggestion
    case e_INVALID_GEN_COUNT: BSLA_FALLTHROUGH;
```
Recent BSLA update

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbblp/mqbblp_remotequeue.cpp
> +                    it = nack(it, ackMessage);
I don't really like the current interface for `mqbi::InlineResult::isPermanentError`. It should be simple yet it's doing several things at once:
1. Checking and returning if an error is permanent.
2. Converting inline result to ack result.
3. Returning ack results via output pointer arg.

I think there is a way to do it simpler:
```suggestion
                if (BSLS_PERFORMANCEHINT_PREDICT_UNLIKELY(
                        mqbi::InlineResult::isPermanentError(rc))) {
                    BSLS_PERFORMANCEHINT_UNLIKELY_HINT;
                    bmqt::AckResult::Enum ackResult = mqbi::InlineResult::toAckResult(rc);

                    bmqp::AckMessage ackMessage;

                    ackMessage.setStatus(
                        bmqp::ProtocolUtil::ackResultToCode(ackResult));
                    it = nack(it, ackMessage);
```

We don't even need to define and pass `ackResult` to a function if there is no error.

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbi/mqbi_queue.h
> +    d_inlineClient_p = inlineClient;
```suggestion
    BSLS_ASSERT_SAFE(inlineClient);

    d_inlineClient_p = inlineClient;
```

From the usage context, `inlineClient` arg is never null. However, we can still add precondition check here just to be sure

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbi/mqbi_queue.h
> +, d_inlineClient_p(original.d_inlineClient_p)
As a side note, I am curious why do we even need to define and update this constructor. It's possible that we only store `QueueHandleRequesterContext` in `shared_ptr`

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbi/mqbi_queue.h
> +// ----------------------------------
```suggestion
// -----------------------
// struct OpenQueueContext
// -----------------------
```

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbi/mqbi_queue.h
> +    // NOTHING
Should we check that `handle` is not null here?
```suggestion
    BSLS_ASSERT_SAFE(handle);
```

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbi/mqbi_queue.h
> +        bsl::shared_ptr<mqbstat::QueueStatsClient> d_clientStats;
```suggestion
        bsl::shared_ptr<mqbstat::QueueStatsClient> d_clientStats_sp;
```

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbi/mqbi_queue.h
> +// ==================================
```suggestion
// =======================
// struct OpenQueueContext
// =======================
```

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbi/mqbi_queue.h
> +    bsl::shared_ptr<mqbstat::QueueStatsClient> d_stats;
```suggestion
    bsl::shared_ptr<mqbstat::QueueStatsClient> d_stats_sp;
```

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbi/mqbi_queue.h
> +    InlineClient* d_inlineClient_p;
Can `QueueHandleRequesterContext` outlive `d_inlineClient_p`?

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbi/mqbi_queue.h
> +
```suggestion

// ==================
// class InlineClient
// ==================

```

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbi/mqbi_queue.h
> +// =======================
```suggestion
// ==================
// class InlineResult
// ==================

```

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbi/mqbi_queue.h
> +#include <bmqst_statcontext.h>
Can we avoid adding this include by forward-declaring `bmqst::StatContext`?

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbi/mqbi_queue.cpp
> +}
```suggestion
}

```

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbc/mqbc_clusterstate.h
> +                                      ClusterNodeSession* ns);
The comment above still mentions `node`, not the `ns`

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbc/mqbc_clusterstate.cpp
> +#include <mqbc_clusternodesession.h>
```suggestion
```
Can remove it, it's in the header for this component already

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbc/mqbc_clusternodesession.h
> +            d_gatePut.close();
I do not understand this comment.
First, it says "do process puts", but `d_gatePut` is being closed right after.
After this, it says something about broadcast, remote queue, stop request, but there is no code here related to broadcast or any context.
Would be nice to rephrase the comment to show what exactly `d_gatePut` is doing first, or, in other words, plan the comment from the concrete details to higher scope.

Something like this:
```
Closing the PUT gate will prevent from posting PUTs from remote to upstream.
However, this doesn't stop processing PUTs on PRIMARY in Stopping state.
As a side effect, broadcast PUTs in RemoteQueue will be lost, because RemoteQueue is not buffering them.
```

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbc/mqbc_clusternodesession.h
> +    }
```suggestion
    // Spin while locked e_CLOSE < result

    while (e_CLOSE < result) {
        bslmt::ThreadUtil::yield();
        result = d_value;
    }
```
Might be more intuitive use "less" operator, so the lesser arg is on the left

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbc/mqbc_clusternodesession.h
> +    }
```suggestion
    return true;
```
Possible to simplify a bit

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbc/mqbc_clusternodesession.h
> +    (void)result;
```suggestion
    BSLA_MAYBE_UNUSED const int result = d_value.subtract(e_ENTER);
    BSLS_ASSERT_SAFE(e_INIT <= result);
```
Alternative

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbc/mqbc_clusternodesession.h
> +    (void)result;
```suggestion
    BSLA_MAYBE_UNUSED const int result = d_value.subtract(e_CLOSE);
    BSLS_ASSERT_SAFE(e_INIT <= result);
    BSLS_ASSERT_SAFE((result & e_CLOSE) == 0);
```
Alternative

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbc/mqbc_clusternodesession.h
> +    if (d_clientStats) {
```suggestion
    if (d_clientStats_sp) {
```
It's helpful to add a `_sp` suffix to this field's name, to make `if` condition more clear.

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbc/mqbc_clusternodesession.h
> +    GateKeeper& gateConfirm();
These 2 are not accessors because they are not `const`-qualified. Let's move to manipulators

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbc/mqbc_clusternodesession.h
> +            unsigned int            queueId) BSLS_KEYWORD_OVERRIDE;
```suggestion
            int                     queueId) BSLS_KEYWORD_OVERRIDE;
```

This arg should be `int` the same way as `sendPush` one. Also, we have a special negative value for `queueId`:

```
static const int k_INVALID_QUEUE_ID = -1;
```

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbc/mqbc_clusternodesession.h
> +    void setNodeStatus(bmqp_ctrlmsg::NodeStatus::Value other,
```suggestion
    /// @brief Update the status of this node session.
    /// @param other Node status of the node this session is
    ///              connected to.
    /// @param self Node status of the self node in relation to
    ///             this session.
    void setNodeStatus(bmqp_ctrlmsg::NodeStatus::Value other,
```

Might be good to explain better what other/self mean in this context

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbc/mqbc_clusternodesession.h
> +    return d_queueHandleRequesterContext_sp->statContext();
I understand that you want to keep only 1 source of truth for stat context, so you removed shared_ptr from `ClusterNodeSession`. However, this makes performance slightly worse than it can be.

There is an extra lookup at `d_queueHandleRequesterContext_sp->` where ref counts are checked, and there is an extra jump to another part of the memory. If we call it often, it's better to keep shared_ptr cached in `ClusterNodeSession`. It is a shared pointer after all

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbc/mqbc_clusternodesession.h
> +            unsigned int            queueId) BSLS_KEYWORD_OVERRIDE;
Another thing, might be better to put `queueId` on the first place in args list.
This way, we first answer `where to send?` and after we answer `what to send?`

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbc/mqbc_clusternodesession.h
> +             const bmqp::Protocol::SubQueueInfosArray& subQueueInfos)
Might be better to put `queueId` on the first place in args list.
This way, we first answer `where to send?` and after we answer `what to send?`

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbc/mqbc_clusternodesession.h
> +        void onEvent(mqbstat::QueueStatsClient::EventType::Enum type,
```suggestion

        // ACCESSORS
        void onEvent(mqbstat::QueueStatsClient::EventType::Enum type,
```

Actually, I am also fine with removing `CREATORS` comment as an alternative

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbc/mqbc_clusternodesession.h
> +    //   (virtual: mqbi::QueueHandleClient)
```suggestion
    //   (virtual: mqbi::InlineClient)
```

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbc/mqbc_clusternodesession.h
> +
```suggestion

    //   (virtual: mqbi::InlineClient)
```

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbc/mqbc_clusternodesession.h
> +class AtomicGate {
We can move AtomicGate/GateKeeper to its separate source file in the future.
It allows to reduce the size of this header for the reader and make it easier to navigate, and we can also cover it with UTs.

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbblp/mqbblp_remotequeue.t.cpp
> +TestBench::PutEvent::PutEvent(const bmqp::PutHeader               header,
```suggestion
TestBench::PutEvent::PutEvent(const bmqp::PutHeader&              header,
```

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbblp/mqbblp_queuesessionmanager.h
> +    if (d_stats) {
```suggestion
    if (d_stats_sp) {
```
Easier to understand what we implicitly convert to `bool`

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbblp/mqbblp_relayqueueengine.cpp
> +                              handleParameters.writeCount()));
```suggestion
    {
        mqbi::QueueHandle::SubStreams::const_iterator citSubStream =
            queueHandle->registerSubStream(
                downstreamInfo,
                upstreamSubQueueId,
                mqbi::QueueCounts(handleParameters.readCount(),
                                  handleParameters.writeCount()));
        context->d_stats = citSubStream->second.d_clientStats;
     }                          
```
Possible to narrow down the lifetime of this `const_iterator`.

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbblp/mqbblp_relayqueueengine.cpp
> +    context->d_stats = citSubStream->second.d_clientStats;
```suggestion
```

Look at the comment above, possible to assign this right after the iterator is retrieved

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbblp/mqbblp_queuesessionmanager.h
>  class StatContext;
Possible to remove this forward declaration if this is included
```
#include <mqbstat_queuestats.h>
```

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbblp/mqbblp_queuesessionmanager.cpp
> +    BSLS_ASSERT_SAFE(statContext);
```suggestion
    BSLS_ASSERT_SAFE(statContext_sp);
```
Helpful to understand what we implicitly convert to `bool`

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbblp/mqbblp_queuesessionmanager.cpp
> +            mqbi::QueueHandleRequesterContext ::generateUniqueRequesterId())
```suggestion
            mqbi::QueueHandleRequesterContext::generateUniqueRequesterId())
```
Don't know if this is a formatter issue...

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbblp/mqbblp_queuehandle.h
> +    typedef bsl::shared_ptr<mqbstat::QueueStatsClient> Stats;
```suggestion
    typedef bsl::shared_ptr<mqbstat::QueueStatsClient> StatsSp;
```

I think it's not good to hide `shared_ptr` from the type name because we can only guess if it is stored by value or is a pointer.

As an example, a few lines below:
```
const Stats d_stats;
```

It is confusing for a reader because they can only guess what is this field. They have to stop and spend time on figuring out that it is actually a shared pointer.

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbblp/mqbblp_queue.h
> +        const mqbi::OpenQueueConfirmationCookie& confirmationCookie,
It's a pity that we hide that `mqbi::OpenQueueConfirmationCookie` is actually a shared pointer. This information might improve code readability

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbblp/mqbblp_clusterqueuehelper.h
> +        const int                                peerInstanceId);
```suggestion
        int                                      peerInstanceId);
```
Not necessary to const-qualify a basic arithmetic type. This code existed before your PR so we don't need to change it now

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbblp/mqbblp_clusterqueuehelper.h
> +        unsigned int                          qId,
```suggestion
        int                               queueId,
```

QueueId can be negative

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbblp/mqbblp_clusterproxy.cpp
> +    rc = d_activeNode_p->channel().writePut(putHeader, appData, state);
```suggestion
    const bmqt::GenericResult::Enum rc = d_activeNode_p->channel().writePut(putHeader, appData, state);
```

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbblp/mqbblp_clusterproxy.cpp
> +    BSLS_ANNOTATION_UNUSED const bsl::shared_ptr<bdlbb::Blob>& options,
```suggestion
    BSLA_UNUSED int                                 partitionId,
    const bmqp::PutHeader&                          putHeader,
    const bsl::shared_ptr<bdlbb::Blob>&             appData,
    BSLA_UNUSED const bsl::shared_ptr<bdlbb::Blob>& options,
```
BSLA_UNUSED

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbblp/mqbblp_clusterproxy.cpp
> +                                                message.messageGUID());
```suggestion
    BSLS_ASSERT_SAFE(d_activeNode_p);
    
    const bmqt::GenericResult::Enum rc = d_activeNode_p->channel().writeConfirm(message.queueId(),
                                                message.subQueueId(),
                                                message.messageGUID());
```

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbblp/mqbblp_clusterproxy.cpp
> +                                const bmqp::ConfirmMessage& message)
```suggestion
ClusterProxy::sendConfirmInline(BSLA_UNUSED int             partitionId,
                                const bmqp::ConfirmMessage& message)
```

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbblp/mqbblp_clusterproxy.cpp
> +    if (!d_activeNode_p) {
Note that `ClusterProxy::processEvent` is called from IO thread.

There is also `ClusterProxy::onActiveNodeDown` that is called from cluster dispatcher thread. It does the following:
```
void ClusterProxy::onActiveNodeDown(...) {
    ...
    d_gateActiveNode.close();
    d_activeNode_p = 0;
}
```

So it's possible that `d_activeNode_p` will change from non-null to null when we run `ClusterProxy::processEvent`. The condition `if (!d_activeNode_p)` might be false, and right after we skip it `d_activeNode_p` becomes NULL. This leads to possible crashes when we dereference it later in this method

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbblp/mqbblp_clusterproxy.cpp
> +                             d_activeNode_p,
Note that we pass a value of the pointer that can be changed to NULL in the meantime. How this code should work if there is `void ClusterProxy::onActiveNodeDown` call from cluster dispatcher thread?

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqba/mqba_clientsession.cpp
> +        subQueueInfoPtr->onEvent(mqbstat::QueueStatsClient::EventType::e_PUT,
Self note: can remove include of QueueStatsClient if a template function is declared

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbblp/mqbblp_cluster.cpp
> +        primary->channel().writeConfirm(id, subId, message.messageGUID());
```suggestion
        primary->channel().writeConfirm(message.queueId(), message.subQueueId(), message.messageGUID());
```

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbblp/mqbblp_cluster.cpp
> +    const int subId = message.subQueueId();
```suggestion
```
Can use directly in 1 place below

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbblp/mqbblp_cluster.cpp
> +    BSLS_ANNOTATION_UNUSED const bsl::shared_ptr<bdlbb::Blob>& options,
```suggestion
    BSLA_UNUSED const bsl::shared_ptr<bdlbb::Blob>& options,
```

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbblp/mqbblp_queuehandle.cpp
> +    unsigned int                       downstreamSubQueueId,
Can subQueueId have a special negative value?

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbblp/mqbblp_queuehandle.cpp
> +            d_producerStats.reset();
The comment says about caching, but the code does the opposite and resets a shared_ptr.

2025-07-07 15:27 UTC, 678098 commented on src/groups/mqb/mqbc/mqbc_clusternodesession.cpp
> +                            unsigned int            queueId)
```suggestion
                           int            queueId)
```
queueId can be negative?

2025-07-15 17:52 UTC, dorjesinpo commented on src/groups/mqb/mqbmock/mqbmock_cluster.cpp
> +                        genCount);
`BSLS_ASSERT_SAFE(d_putFunctor);`

2025-07-15 19:02 UTC, dorjesinpo commented on src/groups/mqb/mqbi/mqbi_queue.h
> +    InlineClient* d_inlineClient_p;
`d_inlineClient_p` is `ClusterNodeSession` which aggregates `QueueHandleRequesterContext`
so, the answer is no but it is not enforced

2025-07-15 19:17 UTC, dorjesinpo commented on src/groups/mqb/mqbc/mqbc_clusternodesession.h
> +            d_gatePut.close();
this comment better be placed in the `if (other == bmqp_ctrlmsg::NodeStatus::E_AVAILABLE)` clause
Rephrasing like
```
            // Even if self is E_STOPPING, do allow PUTs.
            // Otherwise, broadcast PUTs can be lost in the following scenario:
            // This node sends StopRequest to a downstream while some broadcast
            // PUTs "cross" the StopRequest.  
```

2025-07-15 19:21 UTC, dorjesinpo commented on src/groups/mqb/mqbc/mqbc_clusternodesession.h
> +    (void)result;
sure
(`(void)result;` in my view does a better job)

2025-07-15 19:36 UTC, dorjesinpo commented on src/groups/mqb/mqbc/mqbc_clusternodesession.h
> +             const bmqp::Protocol::SubQueueInfosArray& subQueueInfos)
but `queueId` is not "where".  It is one of the attributes of the PUSH

2025-07-15 19:51 UTC, dorjesinpo commented on src/groups/mqb/mqbblp/mqbblp_queue.h
> +        const mqbi::OpenQueueConfirmationCookie& confirmationCookie,
this came as the code transformation.  We can rename it to `OpenQueueConfirmationCookieSp`

2025-07-15 20:13 UTC, dorjesinpo commented on src/groups/mqb/mqbblp/mqbblp_queuehandle.cpp
> +    unsigned int                       downstreamSubQueueId,
No.  There is `bmqp::Protocol::k_DEFAULT_SUBSCRIPTION_ID` (`0`)

2025-07-15 20:20 UTC, dorjesinpo commented on src/groups/mqb/mqbblp/mqbblp_clusterproxy.cpp
> +    if (!d_activeNode_p) {
`ClusterProxy::sendRequest` is dispatcher thread only (`BSLS_ASSERT_SAFE(dispatcher()->inDispatcherThread(this));`)
Sp are `ClusterProxy::onActiveNodeDown`, `ClusterProxy::onActiveNodeUp`

There is `d_activeNode_p` accessing outside of the dispatcher gate nut then it is protected by `d_gateActiveNode`

2025-07-15 20:21 UTC, dorjesinpo commented on src/groups/mqb/mqbblp/mqbblp_clusterproxy.cpp
> +                             d_activeNode_p,
this is the dispatcher thread

2025-07-16 14:29 UTC, dorjesinpo commented
closing in favor of https://github.com/bloomberg/blazingmq/pull/833

2025-07-16 14:29 UTC, closed without merging