Docs: remove "the the" typos
bloomberg/blazingmq pull request #210
Opened 2024-03-13 13:30 UTC by 678098

2024-03-13 14:30 UTC, pniedzielski requested changes
Changes look good, except for the one I noted above.

A few more that I found using `rg -U 'the\s*\n\s*///?\s*the'`:

    src/groups/mwc/mwcu/mwcu_throttledaction.t.cpp
    280:    // 1. Do a 'MWCU_THROTTLEDACTION_THROTTLE' up to and including the
    281:    //    the maximum number of times (within the specified time interval)
    
    src/groups/bmq/bmqimp/bmqimp_event.h
    334:    /// Configure this instance as a message event in write mode with the
    335:    /// the specified `bufferFactory` to allocate blob buffers when needed.
    
    src/groups/bmq/bmqp/bmqp_protocol.h
    1875:    //  QueueId.......: Id of the queue (as advertised during open queue by the
    1876:    //                  the producer of the Put event this Ack is a response
    3380:    /// Construct object indicating MessageProperties presence as the
    3381:    /// the specified `isPresent` with Schema id as the specified `schemaId`
    
    src/groups/bmq/bmqp/bmqp_putmessageiterator.t.cpp
    68://   - Create a valid iterator which allows decompression i.e. the
    69://     the decompress flag is set to true. The iterator has messages which
    
    src/groups/bmq/bmqp/bmqp_pushmessageiterator.t.cpp
    910://   - Create a valid iterator which allows decompression i.e. the
    911://     the decompress flag is set to true. The iterator has messages which

    src/groups/mqb/mqbc/mqbc_recoveryutil.h
    132:    /// This function operates on the record currently being pointed by the
    133:    /// the specified `journalIt`. It uses the specified `dataFd` if the

2024-03-13 14:30 UTC, pniedzielski commented on src/groups/mwc/mwcst/mwcst_statvalue.h
> -        /// value.  For example the max of the added value will the the sum
`will the the sum` -> `will be the sum`?

2024-03-13 21:17 UTC, pniedzielski commented
@678098 I think you may have done a reset by mistake, you requested a review on [49ac1b1](https://github.com/bloomberg/blazingmq/commit/49ac1b15c5fbf8bbbcdef34c52f910f45e2d975f) again, which doesn't include changes from the lineage headed by [439e4f8](https://github.com/bloomberg/blazingmq/commit/439e4f8ef0a9ec3be7ca3a05c0baf1782f796c7d).

2024-03-14 12:39 UTC, 678098 commented
Hi @pniedzielski, fixed

2024-03-14 12:46 UTC, pniedzielski approved these changes
👍

2024-03-14 14:56 UTC, merged