CI: use the latest black formatter version
bloomberg/blazingmq pull request #355
Opened 2024-07-11 00:59 UTC by 678098

2024-07-11 14:54 UTC, kaikulimu commented
@jll63 is also working on this. You two can consolidate on a standard black solution.

2024-07-12 19:58 UTC, jll63 requested changes

2024-07-12 19:58 UTC, jll63 commented on .github/workflows/formatting-check.yaml
> +          sudo apt-get install -y python3.10 python3-pip
Aren't we switching to Python 3.12?

2024-07-12 20:09 UTC, jll63 submitted a review, later dismissed

2024-07-12 20:10 UTC, jll63 approved these changes

2024-07-12 20:37 UTC, merged