Add autoIncremented parameter to batch-post in bmqtool
bloomberg/blazingmq pull request #357
Opened 2024-07-15 15:23 UTC by syuzvinsky

A new parameter 'autoIncremented' can be provided to 'batch-post' command in bmqtool.
It can be used to test subscriptions with expressions like 'x % 3 == 0' where "x" is a value of 'autoIncremented' field, so, every 3rd element will be received by the subscriber.

2024-07-22 11:47 UTC, 678098 requested changes

2024-07-22 11:47 UTC, 678098 commented on src/applications/bmqtool/m_bmqtool_parameters.h
> +    bsl::string                         autoIncrementedField() const;
```suggestion
    const bsl::string&                  autoIncrementedField() const;
```

2024-07-22 11:47 UTC, 678098 commented on src/applications/bmqtool/m_bmqtool_poster.h
> +    unsigned int d_autoIncrementedValue;
```suggestion
    bsls::Types::Uint64 d_autoIncrementedValue;
```

2024-07-22 11:47 UTC, 678098 commented on src/applications/bmqtool/m_bmqtool_poster.h
> +    // the message properties.
Might convert to Doxygen style comment

2024-07-22 15:18 UTC, syuzvinsky commented on src/applications/bmqtool/m_bmqtool_parameters.h
> +    // in batch-posting mode.
The style is derived from the style used for all private variables in this file. Applying doxygen style for just one field looks impractical.

2024-07-22 15:18 UTC, syuzvinsky commented on src/applications/bmqtool/m_bmqtool_poster.h
> +    // the message properties.
the same comment about style uniformity

2024-07-22 15:59 UTC, 678098 commented on src/applications/bmqtool/m_bmqtool_parameters.h
> +inline bsl::string Parameters::autoIncrementedField() const
```suggestion
inline
const bsl::string &Parameters::autoIncrementedField() const
```

2024-07-22 16:06 UTC, 678098 commented on src/applications/bmqtool/m_bmqtool_parameters.h
> +const bsl::string &Parameters::autoIncrementedField() const
Making formatter happy
```suggestion
inline const bsl::string &Parameters::autoIncrementedField() const
```

2024-07-23 10:45 UTC, 678098 approved these changes
LGTM!

2024-07-23 13:07 UTC, merged