Performance[MQB]: prevent unnecessary allocations in root queue engine
bloomberg/blazingmq pull request #390
Opened 2024-08-06 15:46 UTC by 678098

2024-08-08 17:17 UTC, dorjesinpo requested changes
The allocation tables in the description seem to come different scenarios so not much of illustration, but still a good idea.    
Why don't we do the same for the `RelayQueueEngine`?

2024-08-08 17:17 UTC, dorjesinpo commented on src/groups/mqb/mqbblp/mqbblp_rootqueueengine.h
> +    QueueEngineUtil_AppsDeliveryContext d_context;
just a suggestion, since this is a data member now, a bit more descriptive name to disambiguate from other (future) contexts

2024-08-09 12:46 UTC, 678098 commented on src/groups/mqb/mqbblp/mqbblp_rootqueueengine.cpp
> +    d_appsDeliveryContext.d_doRepeat = true;
Note that we do `reset()` when we enter the `while` loop

2024-08-09 14:27 UTC, dorjesinpo submitted a review, later dismissed
Just a minor note wrt `d_doRepeat = true`, a `do` `while` loop could look good

2024-08-09 14:34 UTC, 678098 commented
> Just a minor note wrt `d_doRepeat = true`, a `do` `while` loop could look good

Good suggestion, applied

2024-08-09 14:54 UTC, dorjesinpo approved these changes

2024-08-09 16:01 UTC, merged