Shutdown V2
bloomberg/blazingmq pull request #399
Opened 2024-08-15 14:03 UTC by dorjesinpo

Changing shutdown logic to minimize control plane traffic.

1.  StopRequest is now per App (not Cluster)
2. Downstreams of the the shutting down do not deconfigure queues.  Upstreams do.
3. The shutting down waits for unconfirmed (not the downstreams)

```
DownStream              Shutting down broker:           Upstream

                            InitiateShutdown:
                
                            ClientSessions:
                                changes the state
                    
                            Broker sessions:
                    <--         StopRequest V2          -->

Clusters                                                    Clusters
and                                                             The ClusterNodeSession:
ClusterProxies (CQH):                                               QueueHandles:
    Queues:                                                             deconfigureAll
        buffer PUTs
                                                            ClusterProxies:
                                                                The ClientSession:
                                                                    QueueHandles:
                                                                        deconfigureAll
                    -->         StopResponse V2         <--
            
                            Clusters:
                                stopPushing
                                checkUnconfirmedV2
                        
                                continueShutdownDispatched
                                    change the state(s)
                                    cancelAllRequests
                                    delete (dirty) queues
```

2024-08-29 14:58 UTC, pniedzielski requested changes
Nothing big.  A few questions inline, a pervasive typo, and some comment/docs changes.

## Overall comments

  - Once we remove the v1 shutdown code, this will be a bit simpler.  I think then it might be worth taking a little time to look at simplifying the structure of some of the parts that we've touched here (the separation of labor between `initializeShutdown` vs `stop` in `mqba_application` won't really make sense at that stage).

  - Now that we're open-source, I think we need be a bit more careful about what versions of brokers users may try to run.  I noted that already we might want to turn off support for ungraceful shutdown, since all OSS brokers support it.  But I think we should be intentional about turning off graceful shutdown v1, document when we do it, and provide an upgrade process for this (in the manner of https://kafka.apache.org/documentation/#upgrade).

  - I found this comment in `mqbblp_clusterproxy`'s `ClusterProxy::stopDispatched`:
    ```
    // TBD:  In the future, we should review the entire shutdown logic, and
    //       eventually implement a request/response based mechanism in
    //       order to provide true graceful shutdown.
    ```
    A search revealed that this indeed was from before graceful shutdown logic v1, and from what I understand about this part of the code, this comment can safely be removed.  I think changing some of the `// temporary` comments to something greppable as I noted below will mitigate things like this being left behind from this PR.
    
## Merging

I think we'll need to unrevert Luke's admin API changes before we merge this in.  So either: you can make the changes I suggest here and I'll approve before we unrevert the changes, and I can approve again after you rebase, or you can hold off on making the changes until after we unvert those changes and I'll approve then.

2024-09-03 15:59 UTC, dorjesinpo commented on src/groups/bmq/bmqp/bmqp_requestmanager.h
> +        if (!d_lateResponseMode) {
Yes, this is unrelated.  Some UT(s) were failing allocators check

2024-09-03 16:10 UTC, dorjesinpo commented on src/groups/mqb/mqba/mqba_clientsession.h
> +        // TEMPORARY, remove 'after switching to StopRequest V2
Replacing with `// TODO(shutdown-v2): TEMPORARY, remove when all switch to StopRequest V2.`

2024-09-03 16:20 UTC, dorjesinpo commented on src/groups/mqb/mqbblp/mqbblp_rootqueueengine.cpp
> +        it->value()->reset();
Should we change it? How about `undoRouting`?

2024-09-03 17:02 UTC, dorjesinpo commented on src/groups/mqb/mqba/mqba_application.cpp
> +                continue;  // CONTINUE
Agree, this method should return `false`, if there is a node not supporting `k_GRACEFUL_SHUTDOWN`.
This is more like a leftover from when shutdown v1 was implemented.  Looks like we need a cleanup, why don't we do V0 and v1 together ?

2024-09-03 17:09 UTC, dorjesinpo commented on src/groups/mqb/mqba/mqba_application.cpp
> -    // Note that we must do an out of order stop/destroy with respect to the
`DomainManager` does have a reference to `ClusterCatalog`.  Note this is `stop` method which does not destruct instances.
The  reason for the change is explained in the comment above.

2024-09-03 17:23 UTC, dorjesinpo commented on src/groups/mqb/mqbi/mqbi_cluster.h
> +    /// invoked.  If the optional (temporary) specified 'suppportShutdownV2' is
It should be removed when everything switch to V2

2024-09-09 16:10 UTC, pniedzielski commented on src/groups/mqb/mqbblp/mqbblp_rootqueueengine.cpp
> +        it->value()->reset();
`undoRouting` is a good name for this.  If you want to make that change in this PR or later, either way is okay by me.  Low priority.

2024-09-09 16:12 UTC, pniedzielski commented on src/groups/mqb/mqba/mqba_application.cpp
> +                continue;  // CONTINUE
Doing V0 and V1 together sounds okay to me.

2024-09-09 16:18 UTC, pniedzielski commented on src/groups/mqb/mqbblp/mqbblp_clusterqueuehelper.h
> +    bool d_suppportShutdownV2;
Seems good to me.

2024-09-09 16:23 UTC, pniedzielski commented on src/groups/mqb/mqbblp/mqbblp_clusterqueuehelper.cpp
> +    // Assume Shutdown V2
Comment added below this line. ✅

2024-09-09 16:25 UTC, pniedzielski commented on src/groups/mqb/mqba/mqba_application.cpp
> -    // Note that we must do an out of order stop/destroy with respect to the
I see it now, yes.

2024-09-09 16:27 UTC, pniedzielski submitted a review, later dismissed
👍🏻 

Let me know if you need a re-approval after fixing merge conflicts for getting this into `main`.

2024-09-10 14:20 UTC, pniedzielski approved these changes
Reapproving after rebase to fix merge conflicts.  Spot checked that no accidental changes were made.

2024-09-19 15:18 UTC, pniedzielski approved these changes

2024-09-19 16:40 UTC, merged