Perf[BMQIO]: remove unnecessary function copy
bloomberg/blazingmq pull request #483
Opened 2024-10-28 16:43 UTC by 678098

IO thread should spend 7.5% less cpu

Before:
<img width="800" alt="Screenshot 2024-10-28 at 16 33 12" src="https://github.com/user-attachments/assets/1d5601a1-545a-4ef5-8df1-4ab242060c7d">

2024-10-28 18:23 UTC, 678098 commented on src/groups/bmq/bmqio/bmqio_ntcchannel.cpp
>                  readCallback(bmqio::Status(), &numNeeded, &d_readCache);
```
    bslmt::UnLockGuard<bslmt::Mutex> unlock(&d_mutex);
    // !!!!!!!!! timeout or canceled event might happen
    readCallback(bmqio::Status(), &numNeeded, &d_readCache);
```

https://github.com/bloomberg/blazingmq/blob/8b0c00f58a7336d83d5d083d23eb07bc7045a79c/src/groups/bmq/bmqio/bmqio_ntcchannel.cpp#L645-L655

Here, we have a non-trivial thread race. In the past, we could have emptied the `d_callback` of `NtcRead` between these 2 lines of code. We make a copy of `d_callback` before unlocking a mutex, so we don't access the empty callback. However, it means that we can send another callback from this copy **after** we sent TIMEOUT or EMPTY status.

My PR doesn't fix this race, so we still can send something over this callback. Instead, I make sure not to clear it from another thread, so this reference is always alive. And I also added a post-check for `isComplete()` to return early.

2024-10-30 18:54 UTC, dorjesinpo requested changes
Maybe, we can eliminate `setComplete` now and use `clear` instead?

2024-10-30 19:19 UTC, 678098 commented
> Maybe, we can eliminate `setComplete` now and use `clear` instead?

Done. Made sure that we have `clear` down the code paths where I removed `setComplete`.

2024-11-04 15:30 UTC, dorjesinpo approved these changes

2024-11-04 15:36 UTC, merged