WIP
bloomberg/blazingmq pull request #493
Opened 2024-10-30 22:40 UTC by dorjesinpo

1.  Fix the race when reconfiguring domain in FSM
2. Generate AppKey only once when reconfiguring domain.

2024-11-08 18:50 UTC, kaikulimu requested changes

2024-11-08 18:57 UTC, dorjesinpo commented on src/groups/mqb/mqbblp/mqbblp_rootqueueengine.cpp
> +                       << "never be called for a non-Fanout queue.";
This is no longer singular.  Not sure we want to print the entire collection.  Note that this code never executes.

2024-11-08 18:57 UTC, dorjesinpo commented on src/groups/mqb/mqbblp/mqbblp_rootqueueengine.cpp
> +        BALL_LOG_ERROR << "Invalid queue type for unregistering appId.";
Same comment

2024-11-08 18:58 UTC, dorjesinpo commented on src/groups/mqb/mqbblp/mqbblp_cluster.cpp
> +    // TODO: This should be one call - one QueueUpdateAdvisory for all Apps
In some subsequent PR.  Not the top priority.

2024-11-08 20:01 UTC, kaikulimu commented
Added thought, I think we should never generate appKey at https://github.com/bloomberg/blazingmq/blob/613c5baaa94f2f51b0e6575b29d96a057730b30b/src/groups/mqb/mqbc/mqbc_storageutil.cpp#L2444-L2475

Be courageous and not be afraid of changing existing code :)

2024-11-08 20:32 UTC, dorjesinpo commented on src/groups/mqb/mqbblp/mqbblp_rootqueueengine.cpp
> +    iter = makeSubStream(appId, appKey, upstreamSubQueueId);
The Dynamic Apps feature is immediate.  Over there, we do need to discern Dynamic Apps from domain-configured Apps. `initializeAppId` is one way of doing that.  Then, we need to create the `AppState` object and store the property (statically configured vs dynamically configured) in the object.
For this reason, let's revisit `initializeAppId` and `makeSubStream` after Dynamic Apps introduction.

2024-11-08 20:40 UTC, dorjesinpo commented on src/groups/mqb/mqbblp/mqbblp_queue.cpp
> +    rc = d_localQueue_mp->configure(errorDescription, false);
It is not reconfiguration for the newly created engine.  `true` or `false` did not matter before in this case.  Does matter after queue engine becomes aware of the `isReconfigure` value.

2024-11-08 20:52 UTC, dorjesinpo commented on src/groups/mqb/mqbc/mqbc_clusterutil.h
> +    static void
Both versions are being used

2024-11-08 20:59 UTC, dorjesinpo commented on src/integration-tests/test_appids.py
> +def set_app_ids(cluster: Cluster, app_ids: List[str]):  # noqa: F811
I guess, NO Quality Assurance.  But I am not sure, what tool inserted.  Removing

2024-11-08 21:02 UTC, dorjesinpo commented on src/integration-tests/test_appids.py
> +    cluster.deploy_domains()
I agree, but let's defer it to another PR.  Another way, is to move this test to the `test_restart.py`

2024-11-08 21:15 UTC, dorjesinpo commented
> Added thought, I think we should never generate appKey at
We have been over it at the previous commit when we have added ` || !appIdKeyPairs.empty()`

2024-11-11 17:21 UTC, kaikulimu reviewed
Minor comments

2024-11-11 17:21 UTC, kaikulimu commented on src/groups/mqb/mqbblp/mqbblp_rootqueueengine.cpp
> +                       << "never be called for a non-Fanout queue.";
Just printing the queue uri would be nice.

2024-11-11 17:21 UTC, kaikulimu commented on src/groups/mqb/mqbblp/mqbblp_rootqueueengine.cpp
> +        BALL_LOG_ERROR << "Invalid queue type for unregistering appId.";
Just printing the queue uri would be nice.

2024-11-11 17:21 UTC, kaikulimu commented on src/groups/mqb/mqbi/mqbi_queueengine.cpp
> +    BSLS_ANNOTATION_UNUSED const mqbi::Storage::AppInfos& appIdKeyPairs)
Still needs to be changed in this `.cpp` file.

2024-11-11 17:21 UTC, kaikulimu commented on src/groups/mqb/mqbi/mqbi_queueengine.cpp
> +    BSLS_ANNOTATION_UNUSED const mqbi::Storage::AppInfos& appIdKeyPairs)
Still needs to be changed in this `.cpp` file.

2024-11-11 18:00 UTC, merged