WIP
bloomberg/blazingmq pull request #507
Opened 2024-11-08 00:02 UTC by dorjesinpo

WIP

2024-11-18 22:28 UTC, kaikulimu commented on src/groups/mqb/mqbc/mqbc_clusterutil.cpp
> +        if (qcit != domIt->second->queuesInfo().cend()) {
This approach doesn't actually work. Assignment is a different story than unassignment. During first pending assignment, the queue does not exist in `ClusterState` yet, so `qcit` won't find anything, and thus won't set anything to `k_ASSIGNING`. 

*Lemma*: If the queue exists in `ClusterState`, then it is never in `k_ASSIGNING` state.

Therefore, we need a separate collection to keep track of `k_ASSIGNING` queues, and once assignment at `ClusterState` completes, we need to remove the corresponding entry.

2024-11-26 18:05 UTC, kaikulimu commented
Some notes for myself

`ClusterQueueHelper::onQueueAssigned`:
    - Legacy mode: Same observer callback, but skipped due to immediate return
    - FSM mode: Observer callback of `ClusterState::assignQueue`

`ClusterQueueHelper::onQueueAssigning`:
    - Legacy mode: Called during `ClusterStateManager::assignQueue`, `ClusterStateManager::registerQueueInfo`, `ClusterStateManager::processQueueAssignmentRequest`, `ClusterStateManager::processQueueAssignmentAdvisory`
    - FSM mode: Called during `ClusterStateManager::assignQueue`, `ClusterStateManager::registerQueueInfo`, `ClusterStateManager::processQueueAssignmentRequest`
    > Both modes share the same first three codepaths via `ClusterUtil`
    > `ClusterStateManager::processQueueAssignmentRequest` simply fowards to `ClusterUtil::assignQueue`
    > `mqbblp::ClusterStateManager::processQueueAssignmentAdvisory` is unique to legacy mode

`ClusterQueueHelper::onQueueUnassigned`:
    - Legacy mode: Same observer callback, but skipped due to immediate return
    - FSM mode: Observer callback of `ClusterState::unassignQueue`
    
`ClusterQueueHelper::onQueueUnassigning`:
    - Legacy mode: Called during [`ClusterStateManager::processQueueUnAssignmentAdvisory`](https://github.com/bloomberg/blazingmq/blob/main/src/groups/mqb/mqbblp/mqbblp_clusterstatemanager.cpp#L1954)
    - FSM mode: no-op
    > In legacy mode, on the leader, `removeQueueRaw` is called during `ClusterQueueHelper::gcExpiredQueue`

2024-12-04 08:45 UTC, kaikulimu commented
Reviewing, should be done by Dev 5

2024-12-05 07:19 UTC, kaikulimu commented
Progress update:
Queue unassignment flow has been reviewed.
Now moving on to queue assignment flow.

I have refrained from posting my review, in case my perception on queue unassignment aspects changes after I review queue assignment flow.

2024-12-06 08:41 UTC, kaikulimu requested changes
Review done. Thanks for the hard work! This part of the code is not easy to navigate.

2024-12-06 08:41 UTC, kaikulimu commented on src/groups/mqb/mqbblp/mqbblp_clusterqueuehelper.cpp
> -    // NOTE: See TBD in 'onGetDomainDispatched': if the request comes from a
To be honest, I am quite unfamiliar with logic surrounding 'clientIdentity'. Are you sure it is safe to remove this code block?

2024-12-06 08:41 UTC, kaikulimu commented on src/groups/mqb/mqbblp/mqbblp_clusterqueuehelper.cpp
> +            // 'onOpenQueueResponse'
A similar situation occurs during [`ClusterQueueHelper::onQueueAssigned`](https://github.com/bloomberg/blazingmq/blob/ea72c8e4362c0e467531139202cc2b8a697904f8/src/groups/mqb/mqbblp/mqbblp_clusterqueuehelper.cpp#L4031-L4061) in this PR, where you decided to put `if (d_cluster_p->isCSLModeEnabled()) {}` around the block.

This is a satisfactory solution too, if you don't want to refactor too much more code.

2024-12-06 20:20 UTC, dorjesinpo commented on src/groups/mqb/mqbc/mqbc_clusterutil.cpp
> -    queueAssigningCb(uri, false);  // processingPendingRequests
That is the main purpose of this PR.  We want to minimize and straighten the assignment logic.

2024-12-07 18:23 UTC, dorjesinpo commented on src/groups/mqb/mqbblp/mqbblp_clusterqueuehelper.cpp
> +    domainState.adjustQueueCount(1);
Bad idea, actually,  `ClusterState::assignQueue` can be called multiple times leading to a miscounting
See `test_max_queue_restore[multi_node_fsm]`

2024-12-10 03:58 UTC, kaikulimu approved these changes
lgtm

2024-12-10 04:01 UTC, merged