Fix[MQB]: respect protocol file size limits
bloomberg/blazingmq pull request #539
Opened 2024-12-06 00:43 UTC by 678098

Before this PR, it was possible to set a file size not complaint to the protocol limitations. In this case, the cluster will work until it gets the first offset overflow, and then crash.

This PR:
- Adds precise pre-calculated constants for DATA, JOURNAL, QLIST file sizes hard limits.
- Adds the 1st line of checks in `mqbblp::StorageManager::start` (for non-FSM) and `mqbc::StorageManager::start` (for FSM) to gracefully return a failure RC with file size overflow.
- Adds the 2nd line of checks (asserts in `FileStoreSet::setDataFileSize` etc), they should be never triggered in a normal workflow but left here just to be sure.
- Improve consistency of RCs returned from [`mqbblp`/`mqbc`]`::StorageManager::start`
- Add UT to check file size hard limits for `mqbc::StorageManager` (there are no UTs for `mqbblp::StorageManager`).

2024-12-06 07:24 UTC, 678098 commented on src/groups/mqb/mqbs/mqbs_filestoreprotocol.h
> +//                                                        or 16GiB - 8B
```suggestion
//                                                        or 16GiB - 4B
```

2024-12-06 07:24 UTC, 678098 commented on src/groups/mqb/mqbs/mqbs_filestoreprotocol.h
> +//                                                        or 16GiB - 8B
```suggestion
//                                                        or 16GiB - 4B
```

2024-12-11 08:40 UTC, kaikulimu requested changes
One minor comment

2024-12-11 08:40 UTC, kaikulimu commented on src/groups/mqb/mqbc/mqbc_storagemanager.t.cpp
> +            ASSERT_EQ_D("line: " << line << ", expected failure: "
```suggestion
            BMQTST_ASSERT_EQ_D("line: " << line << ", expected failure: "
```

2024-12-11 08:42 UTC, kaikulimu commented on src/groups/mqb/mqbc/mqbc_storagemanager.t.cpp
> +            ASSERT_EQ_D("line: " << line << ", expected failure: "
Might to update with base branch before this can compile

2024-12-11 09:09 UTC, kaikulimu approved these changes

2024-12-11 09:57 UTC, merged