Support TLS listeners
bloomberg/blazingmq pull request #549
Opened 2024-12-16 19:05 UTC by hallfox

Added
=====

- TLS configuration in broker config
- Helper script for generating test certs and CAs
- TLS options for NtcChannel
- Loading certificates and authority data specified from bmqbrkrcfg.json
- SessionOptions to bmq package for configuring client sessions
- --tls-authority and --tls-version options to bmqtool to configure session options
- Client sessions will now require broker TLS sessions when TLS protocol versions are specified
- Create CertificateStore component for bmqio
- Integration tests for TLS

Changed
=======

- Update ntf-core and bde dependencies

2024-12-18 19:15 UTC, chrisbeard reviewed
Very quick pass on the draft

2024-12-18 20:26 UTC, hallfox commented on src/applications/bmqbrkr/etc/bmqbrkrcfg.json
> +            "consoleSeverityThreshold": "TRACE",
No, seems like a leftover from local testing

2025-02-26 21:59 UTC, chrisbeard commented on src/groups/bmq/bmqio/bmqio_ntcchannel.h
> +#include <string_view>
nit: looks like an extra header

2025-03-06 16:10 UTC, 678098 commented
@hallfox I have applied my fixes in this PR:
https://github.com/hallfox/blazingmq/pull/1

2025-03-26 15:06 UTC, emelialei88 requested changes

2025-03-26 20:17 UTC, emelialei88 commented on src/groups/mqb/mqbnet/mqbnet_tcpsessionfactory.cpp
> +        negotiationInit(channel, context);
Isn't this function called only in `else` branch?

2025-04-03 15:03 UTC, dorjesinpo reviewed
few questions

2025-04-03 15:03 UTC, dorjesinpo commented on src/groups/bmq/bmqio/bmqio_ntcchannelfactory.cpp
> +                        callback(event, upgradeStatus, channel);
Is this not enough to inject the upgrade before calling `TCPSessionFactory::channelStateCallback`?

Why do we need `d_upgradeSignaler`?

Same for `processChannelResult`

2025-05-29 16:27 UTC, hallfox commented on src/groups/mqb/mqbnet/mqbnet_tcpsessionfactory.cpp
> +                      << "TCPSessionFactory '" << d_threadName
Think this is an old artifact of a previous iteration, cleaning them up.

2026-03-19 15:24 UTC, pniedzielski requested changes
A few partial comments as I make my way through this

2026-03-19 15:24 UTC, pniedzielski commented on .gitignore
> -*.bak
Not sure we need this change

2026-03-19 15:24 UTC, pniedzielski commented on bin/build-darwin.sh
> -REQ_PKGS=(cmake flex bison google-benchmark googletest ninja pkg-config zlib)
`build-darwin.sh` on `main` builds NTF with `zlib`, without `lz4` and `zstd` (none are needed by BlazingMQ, but we already have `zlib` as a dependency, so no harm).  But, I think we should avoid introducing extra required build depends that we don't need or use.  ntf already committed that sin by making these default to on, let's stop the generational trauma.

2026-03-19 15:24 UTC, pniedzielski commented on bin/build-darwin.sh
> +    git clone --depth 1 --branch 2.6.6 https://github.com/bloomberg/ntf-core.git "${DIR_THIRDPARTY}/ntf-core"
`main` has a newer version of `ntf-core` already

2026-03-19 15:24 UTC, pniedzielski commented on bin/build-fuzz.sh
> +    git clone --depth 1 --branch 2.6.6 https://github.com/bloomberg/ntf-core.git "${DIR_THIRDPARTY}/ntf-core"
main has a newer version of ntf-core already

2026-03-19 15:24 UTC, pniedzielski commented on bin/build-ubuntu.sh
> +    git clone --depth 1 --branch 2.6.6 https://github.com/bloomberg/ntf-core.git "${DIR_THIRDPARTY}/ntf-core"
main has a newer version of ntf-core already

2026-03-19 15:24 UTC, pniedzielski commented on docker/cluster/config/bmqbrkrcfg.json
> +                        "port": 30115,
Nit: let's pick a port between `32800` and `32999` as our default TLS port (let's chat on the side).

2026-03-19 15:24 UTC, pniedzielski commented on docker/sanitizers/build_sanitizer.sh
> +    liblz4-dev \
Same here, let's not introduce extra compression algo dependencies where we don't use them.

2026-03-19 15:24 UTC, pniedzielski commented on docker/single-node/config/bmqbrkrcfg.json
> +                        "port": 30115,
Same comment as above, let's choose a different default port.

2026-03-19 15:24 UTC, pniedzielski commented on docker/build_deps.sh
> +    fetch_git bloomberg ntf-core 2.6.6
Updated on `main`

2026-03-19 15:24 UTC, pniedzielski commented on docker/Dockerfile
> +    liblz4-dev \
Same, compression algorithm comment.

2026-03-19 15:24 UTC, pniedzielski commented on src/applications/bmqtool/m_bmqtool_parameters.cpp
> +, d_sequentialMessagePattern(allocator)
Is this to explicitly initialize all the fields of Parameters, or is there something deeper/more subtle I missed?

2026-03-19 15:24 UTC, pniedzielski commented on src/groups/bmq/bmqimp/bmqimp_application.cpp
> +    } break;
Warning here

2026-03-26 22:11 UTC, 678098 commented
Reviewed here: https://github.com/bloomberg/blazingmq/pull/1223

2026-07-08 22:45 UTC, closed without merging

2026-07-08 22:45 UTC, hallfox commented
It's so over